### ISSUE TITLE
Find Fantasy Models for NPCs

### ISSUE THREAD

**Issue by zenithzyie** [zenithzyie/HighMedievalFantasy#2]
**Describe the feature you would like**
We need character models for the NPCs! 
-Wizard
-Chef Lady
-Village Fool
-Chill Farmer
-Angry Blacksmith
-Tavern Keeper

**Describe the benefit of this feature**
NPCs would exist

**Comment by JacklynnB** [comment]
I have found A pack of medieval characters that I think would work well.
LowPoly Medieval Character - Deltain studio
![yeahyeahyeahyeahyeah](https://github.com/zenithzyie/HighMedievalFantasy/assets/165179420/5a890bd6-8818-46ce-97f7-8d21a1263ad9)

**Comment by zenithzyie** [comment]
This works good !
