### ISSUE TITLE
Environment Design - Farmland Blockout

### ISSUE THREAD

**Issue by zenithzyie** [zenithzyie/HighMedievalFantasy#5]
**Describe the feature you would like**
Farmer needs to have a farm.

Should have:
- [x] Area for dragons
- [x] Farmland with crops
- [x] Farmhouse
- [x] Wizard area (because he's homeless and stays on the farm)
- [x] Barn

**Describe the benefit of this feature**
We need to know where the farm stuff will be

**Comment by MateoSlndr** [comment]
I already started part of the farmland

**Comment by zenithzyie** [comment]
Farmland all good!
